server:
  error:
    include-stacktrace: never

spring:
  datasource:
  url: jdbc:mysql://localhost:3306/SchoolManagementApplication
  username: root
  password: password

  jpa:
    hibernate:
      ddl-auto: update